# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bigindex-solr}
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["openplaces.org"]
  s.date = %q{2009-10-15}
  s.description = %q{longer description of your gem}
  s.email = %q{bigrecord@openplaces.org}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bigindex-solr.gemspec",
     "examples/bigindex.yml",
     "install.rb",
     "lib/bigindex-solr.rb",
     "lib/bigindex-solr/tasks.rb",
     "lib/tasks/bigindex_solr.rake",
     "schema.xml",
     "solr/CHANGES.txt",
     "solr/LICENSE.txt",
     "solr/NOTICE.txt",
     "solr/etc/jetty.xml",
     "solr/etc/webdefault.xml",
     "solr/lib/commons-codec-1.3.jar",
     "solr/lib/commons-csv-0.1-SNAPSHOT.jar",
     "solr/lib/commons-fileupload-1.2.jar",
     "solr/lib/commons-io-1.2.jar",
     "solr/lib/easymock.jar",
     "solr/lib/jetty-6.1.3.jar",
     "solr/lib/jetty-util-6.1.3.jar",
     "solr/lib/jsp-2.1/ant-1.6.5.jar",
     "solr/lib/jsp-2.1/core-3.1.1.jar",
     "solr/lib/jsp-2.1/jsp-2.1.jar",
     "solr/lib/jsp-2.1/jsp-api-2.1.jar",
     "solr/lib/lucene-analyzers-2007-05-20_00-04-53.jar",
     "solr/lib/lucene-core-2007-05-20_00-04-53.jar",
     "solr/lib/lucene-highlighter-2007-05-20_00-04-53.jar",
     "solr/lib/lucene-snowball-2007-05-20_00-04-53.jar",
     "solr/lib/lucene-spellchecker-2007-05-20_00-04-53.jar",
     "solr/lib/servlet-api-2.4.jar",
     "solr/lib/servlet-api-2.5-6.1.3.jar",
     "solr/lib/xpp3-1.1.3.4.O.jar",
     "solr/solr/README.txt",
     "solr/solr/bin/abc",
     "solr/solr/bin/abo",
     "solr/solr/bin/backup",
     "solr/solr/bin/backupcleaner",
     "solr/solr/bin/commit",
     "solr/solr/bin/optimize",
     "solr/solr/bin/readercycle",
     "solr/solr/bin/rsyncd-disable",
     "solr/solr/bin/rsyncd-enable",
     "solr/solr/bin/rsyncd-start",
     "solr/solr/bin/rsyncd-stop",
     "solr/solr/bin/scripts-util",
     "solr/solr/bin/snapcleaner",
     "solr/solr/bin/snapinstaller",
     "solr/solr/bin/snappuller",
     "solr/solr/bin/snappuller-disable",
     "solr/solr/bin/snappuller-enable",
     "solr/solr/bin/snapshooter",
     "solr/solr/conf/admin-extra.html",
     "solr/solr/conf/protwords.txt",
     "solr/solr/conf/schema.xml",
     "solr/solr/conf/scripts.conf",
     "solr/solr/conf/solrconfig.xml",
     "solr/solr/conf/stopwords.txt",
     "solr/solr/conf/synonyms.txt",
     "solr/solr/conf/xslt/example.xsl",
     "solr/solr/conf/xslt/example_atom.xsl",
     "solr/solr/conf/xslt/example_rss.xsl",
     "solr/solr/data/development/index/_a.fdt",
     "solr/solr/data/development/index/_a.fdx",
     "solr/solr/data/development/index/_a.fnm",
     "solr/solr/data/development/index/_a.frq",
     "solr/solr/data/development/index/_a.nrm",
     "solr/solr/data/development/index/_a.prx",
     "solr/solr/data/development/index/_a.tii",
     "solr/solr/data/development/index/_a.tis",
     "solr/solr/data/development/index/_a_1.del",
     "solr/solr/data/development/index/_b.fdt",
     "solr/solr/data/development/index/_b.fdx",
     "solr/solr/data/development/index/_b.fnm",
     "solr/solr/data/development/index/_b.frq",
     "solr/solr/data/development/index/_b.nrm",
     "solr/solr/data/development/index/_b.prx",
     "solr/solr/data/development/index/_b.tii",
     "solr/solr/data/development/index/_b.tis",
     "solr/solr/data/development/index/_b_1.del",
     "solr/solr/data/development/index/_c.fdt",
     "solr/solr/data/development/index/_c.fdx",
     "solr/solr/data/development/index/_c.fnm",
     "solr/solr/data/development/index/_c.frq",
     "solr/solr/data/development/index/_c.nrm",
     "solr/solr/data/development/index/_c.prx",
     "solr/solr/data/development/index/_c.tii",
     "solr/solr/data/development/index/_c.tis",
     "solr/solr/data/development/index/_c_1.del",
     "solr/solr/data/development/index/segments.gen",
     "solr/solr/data/development/index/segments_q",
     "solr/start.jar",
     "solr/webapps/solr.war",
     "spec/bigindex-solr_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://bigrecord.org}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{one-line summary of your gem}
  s.test_files = [
    "spec/bigindex-solr_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
